repo_url: https://github.com/web-classroom/heig-vd-web-course
repo_name: web-classroom/heig-vd-web-course
site_name: HEIG-VD WEB-A VGX Wednesday Course
site_url: https://web-classroom.github.io/heig-vd-web-course/
site_description: >-
  The main repository for the WEB course (VGX, Wednesday, 2024)
copyright: https://github.com/web-classroom/heig-vd-web-course/blob/main/LICENSE.md
edit_uri: blob/main/docs/
theme:
  favicon: assets/images/favicon.svg
  language: en
  icon:
    logo: material/school
    repo: fontawesome/brands/git-alt
  name: material
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - content.action.edit
    - content.code.annotate
    - content.code.copy
    - navigation.footer
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.suggest
    - search.highlight
    - toc.follow
plugins:
  - plantuml:
      puml_url: http://plantuml:8080
      puml_keyword: plantuml
  - glightbox
  - awesome-pages:
      filename: pages.yaml
      collapse_single_pages: true
  - search
  - tags
extra:
  social:
    - icon: material/github
      link: https://github.com/HEIG-VD-WEB/web-course
      name: Web on Github
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.details
  # - pymdownx.emoji:
  #     emoji_index: !!python/name:material.extensions.emoji.twemoji
  #     emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
      base_path: ["docs"]
      auto_append:
        - glossary/index.md
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - tables
  - toc:
      permalink: true
# extra_css:
#   - assets/stylesheets/extra.css
# extra_javascript:
#   - assets/javascripts/extra.js
